---
version: "3.9"

services:
  mycroft_api:
    container_name: mycroft_api
    hostname: mycroft_api
    restart: unless-stopped
    image: smartgic/mycroft-api:latest
    network_mode: host
    environment:
      SECRET: ${SECRET}
      WS_HOST: ${WS_HOST}
      WS_PORT: ${WS_PORT}
      API_KEY: ${API_KEY}
      USERS_DB: ${USERS_DB}
    volumes:
      - ./users.json:/users.json:ro
